//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saw.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Saw.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 指令格式有問題 , 請洽程式人員 !!! 的當地語系化字串。
        /// </summary>
        internal static string Text_Saw_CommandFormat_Error {
            get {
                return ResourceManager.GetString("Text_Saw_CommandFormat_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Command format error , please contact the engineer !!! 的當地語系化字串。
        /// </summary>
        internal static string Text_Saw_CommandFormat_Error_En {
            get {
                return ResourceManager.GetString("Text_Saw_CommandFormat_Error_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未定義的指令 : \&quot; 的當地語系化字串。
        /// </summary>
        internal static string Text_Saw_CommandProcess_Undefined1 {
            get {
                return ResourceManager.GetString("Text_Saw_CommandProcess_Undefined1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Undefined command :  \&quot; 的當地語系化字串。
        /// </summary>
        internal static string Text_Saw_CommandProcess_Undefined1_En {
            get {
                return ResourceManager.GetString("Text_Saw_CommandProcess_Undefined1_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 \&quot; , 請洽程式人員 !!! 的當地語系化字串。
        /// </summary>
        internal static string Text_Saw_CommandProcess_Undefined2 {
            get {
                return ResourceManager.GetString("Text_Saw_CommandProcess_Undefined2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 \&quot; , please contact the engineer !!! 的當地語系化字串。
        /// </summary>
        internal static string Text_Saw_CommandProcess_Undefined2_En {
            get {
                return ResourceManager.GetString("Text_Saw_CommandProcess_Undefined2_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Destroy Action 資料格式有問題 , 請洽程式人員 !!! 的當地語系化字串。
        /// </summary>
        internal static string Text_Saw_DestroyAction_DataFormat_Error {
            get {
                return ResourceManager.GetString("Text_Saw_DestroyAction_DataFormat_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Destroy Action has some wrong data format , please contact the engineer !!! 的當地語系化字串。
        /// </summary>
        internal static string Text_Saw_DestroyAction_DataFormat_Error_En {
            get {
                return ResourceManager.GetString("Text_Saw_DestroyAction_DataFormat_Error_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &quot;GetResult 錯誤的呼叫 !!! (&quot; 的當地語系化字串。
        /// </summary>
        internal static string Text_Saw_GetResult_Error {
            get {
                return ResourceManager.GetString("Text_Saw_GetResult_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &quot;Calling GetResult error !!! (&quot; 的當地語系化字串。
        /// </summary>
        internal static string Text_Saw_GetResult_Error_En {
            get {
                return ResourceManager.GetString("Text_Saw_GetResult_Error_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 LowerCCDCompensation 資料格式有問題 , 請洽程式人員 !!! 的當地語系化字串。
        /// </summary>
        internal static string Text_Saw_LowerCCDCompensation_DataFormat_Error {
            get {
                return ResourceManager.GetString("Text_Saw_LowerCCDCompensation_DataFormat_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 LowerCCDCompensation has some wrong data format , please contact the engineer !!! 的當地語系化字串。
        /// </summary>
        internal static string Text_Saw_LowerCCDCompensation_DataFormat_Error_En {
            get {
                return ResourceManager.GetString("Text_Saw_LowerCCDCompensation_DataFormat_Error_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請問你確定要歸零{0}嗎? 的當地語系化字串。
        /// </summary>
        internal static string Text_Saw_Question_Home {
            get {
                return ResourceManager.GetString("Text_Saw_Question_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Are you sure to zero {0}? 的當地語系化字串。
        /// </summary>
        internal static string Text_Saw_Question_Home_En {
            get {
                return ResourceManager.GetString("Text_Saw_Question_Home_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 通訊收取命令太長 (&gt;1000) ! 的當地語系化字串。
        /// </summary>
        internal static string Text_Saw_Receive_Command_Too_Long {
            get {
                return ResourceManager.GetString("Text_Saw_Receive_Command_Too_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Communication receive command too long (&gt;1000) ! 的當地語系化字串。
        /// </summary>
        internal static string Text_Saw_Receive_Command_Too_Long_En {
            get {
                return ResourceManager.GetString("Text_Saw_Receive_Command_Too_Long_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &quot;ResetResult 錯誤的呼叫 !!! (&quot; 的當地語系化字串。
        /// </summary>
        internal static string Text_Saw_ResetResult_Error {
            get {
                return ResourceManager.GetString("Text_Saw_ResetResult_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &quot;Calling ResetResult error !!! (&quot; 的當地語系化字串。
        /// </summary>
        internal static string Text_Saw_ResetResult_Error_En {
            get {
                return ResourceManager.GetString("Text_Saw_ResetResult_Error_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角度大於十度!! 的當地語系化字串。
        /// </summary>
        internal static string Text_Saw_RotateCorrect_Angle_Over_Ten {
            get {
                return ResourceManager.GetString("Text_Saw_RotateCorrect_Angle_Over_Ten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Angle greater than 10 degree!! 的當地語系化字串。
        /// </summary>
        internal static string Text_Saw_RotateCorrect_Angle_Over_Ten_En {
            get {
                return ResourceManager.GetString("Text_Saw_RotateCorrect_Angle_Over_Ten_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &quot;SendData 錯誤的呼叫 !!! (&quot; 的當地語系化字串。
        /// </summary>
        internal static string Text_Saw_SendData_Error {
            get {
                return ResourceManager.GetString("Text_Saw_SendData_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &quot;Calling SendData error !!! (&quot; 的當地語系化字串。
        /// </summary>
        internal static string Text_Saw_SendData_Error_En {
            get {
                return ResourceManager.GetString("Text_Saw_SendData_Error_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SetPackageName 資料格式有問題 , 請洽程式人員 !!! 的當地語系化字串。
        /// </summary>
        internal static string Text_Saw_SetPackageName_DataFormat_Error {
            get {
                return ResourceManager.GetString("Text_Saw_SetPackageName_DataFormat_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SetPackageName has some wrong data format , please contact the engineer !!! 的當地語系化字串。
        /// </summary>
        internal static string Text_Saw_SetPackageName_DataFormat_Error_En {
            get {
                return ResourceManager.GetString("Text_Saw_SetPackageName_DataFormat_Error_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Vacuum Action 資料格式有問題 , 請洽程式人員 !!! 的當地語系化字串。
        /// </summary>
        internal static string Text_Saw_VacuumAction_DataFormat_Error {
            get {
                return ResourceManager.GetString("Text_Saw_VacuumAction_DataFormat_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Vacuum Action has some wrong data format , please contact the engineer !!! 的當地語系化字串。
        /// </summary>
        internal static string Text_Saw_VacuumAction_DataFormat_Error_En {
            get {
                return ResourceManager.GetString("Text_Saw_VacuumAction_DataFormat_Error_En", resourceCulture);
            }
        }
    }
}
